### ISSUE TITLE
MetalMax 3 graphics plugin

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#205]
Console: NDS
Format extension(s): .Tex
Original game name: Metalmax 3

First 8 byte of file(s):
.tex - [43484E4B00000000] - [CHNK]

More details?:
**Note: some are compressed with LZ11 or RLE.**
There are two types of .tex files:
**.tex  with 2 chunks** (graphics + palette)> They can be seen in their entirety in kukii but it is still pending implement the option to save the changes.

**.tex with 3 chunks** (has a TX4I chunk) (graphics + palette indexes(4x4textel) + palette) >Not fully implemented visualization. Is still pending implement the option to save the changes.

**Issues:**
Since version 1.08 of Kuriimu there are some .Texs that previously opened that do not in this version also some do not show up well.
**Error Screen**
![captura de pantalla 183](https://user-images.githubusercontent.com/29298680/30038023-8d602c8a-91b8-11e7-81bc-6deb18918515.png)

Sample files (if possible):
https://mega.nz/#F!A1gCRIqb!fgnKLOhlPDcs_9mOULxjUA

**Comment by onepiecefreak3** [comment]
Since this is more of a bug report for a bug that doesn't exist in K2 anymore, this will be closed.
The plugin for Kuriimu2 has at least the same capacities as the one in Kukkii, and improved upon them with the new image library and TX4I decoding. Refer to Kuriimu2 for future bug reports on this plugin.
