### ISSUE TITLE
Attack on Titan - Escape from Certain Death 

### ISSUE THREAD

**Issue by Moonstriker** [IcySon55/Kuriimu#275]
Console: 3ds
Format extension(s): 
Original game name: Shingeki no Kyojin: Shichi Kara no Dasshutsu

First 8 byte of file(s):
Hex - [20 20 00 00 00 00 00 00]

More details:
I extracted the files and tried to find the text files. I couldn't find them. Because of this, I have been unable to create plugins as well. 

Sample files (if possible): 
https://mega.nz/#!lwZxDJJQ!yot3gIDU1T85LgTvPjWiKGsqQr0BedtC0iXI0Vfq7VQ (Link to DATA.BIN)

**Comment by onepiecefreak3** [comment]
You can't link to the whole game. Even as a link that is too illegal!
Link removed!

**Comment by onepiecefreak3** [comment]
Karameru has now support for the DATA.BIN archive, which seems to also contain textdata.
The files were ZLib compressed, so obviously you couldn't find the text.
I would like you to try the plugin out. Load and Save DATA.BIN with it and rebuild your game with the saved DATA.BIN and tell us if the game crashes or not.

The next step will be the text you asked for I suppose.

**Comment by Moonstriker** [comment]
Jesus. Sorry about the link. I'll keep in mind next time.

**Comment by Moonstriker** [comment]
Know this sounds stupid but I've been trying for hours to try and make this plugin. I looked through all of the references as you asked. Everything looked so complex (even though it probably isn't). 
I honestly don't want you to make one because you're probably busy and I need to know how to make this plugin. The files are probably too compressed too work with.

**Comment by onepiecefreak3** [comment]
It's rly just simple ZLib. If you look at the header of on file you will see that first 2 bytes are 0x78DA everytime. A common header for ZLib compression. You can look into the plugin for this archive and see what I did. It's rly simple if you understand it.

A quick excourse in this format:
Header (0x10 length, every value as integer)
- Magic "CDAR"
- section count
- file count
- unkown
Table of probably filename hashes (ordered from lowest to greatest hash value)
- section count * crc32 entries
fileEntry table (3 integer per entry, every value as integer)
- offset
- decompressed Size
- compressed Size
And the FileData itself which is ZLib compressed.

**Comment by onepiecefreak3** [comment]
Also the issues are for exactly that purpose to request format support. We are busy solving exactly those issues so don't worry :)

**Comment by onepiecefreak3** [comment]
Giving you also a quick reference of what I used in this plugin:

- BinaryReaderX/BinaryWriterX:
A derived BinaryReader/Writer from C# with additional very helpful functions
For example ReadStruct<type>(), which will take in a class or struct and reads the given filestream in the manner you defined the class or struct. The simplest example is the reading of the archive header.
Or ReadMultiple<type>(count) which also takes a simple data type or class/struct to read like ReadStruct<type>() but repeats that multiple times in a row.
The same thing is possible in he Writer. There exists a function called WriteStruct for example.

- FileInfo
Is an interface given by Karameru itself. It provides basic variables to store a file and let it show in the Karameru UI.
Parameters are State (Archived, Replaced and so on), FileName and FileData.
Like in every archive plugin we can also derive from that FileInfo (in the support.cs of the plugin) and add more variables like hashes, entries and whatnot.
We also sometimes override the FileData and/or Filesize if files are archived compressed. We can override the getter of FileData and let it give back the decompressed file instead of the archived compressed one.

I hope this basic reference to both core parts in archive plugins could help in understanding it in general. If you have further question we're glad to answer you on Discord.

**Comment by Moonstriker** [comment]
I tried out the plugin, loaded and saved Data.Bin with it, rebuilt the .cia, and the game crashed once I used it, unfortunately.

**Comment by onepiecefreak3** [comment]
Did you change the text like I suggested? Because without being edited it's most unlikely that it would crash.

**Comment by onepiecefreak3** [comment]
(If you read the comment before this, which is deleted by now... I mixed things up)
Then I know why. The ZLib compressed files had data in their padding. I don't know if that is anything useful, but it seems so. That will be hard.

**Comment by Moonstriker** [comment]
I saved the original data.bin in case anything didn't go as planned.

**Comment by onepiecefreak3** [comment]
Well, I have to try some things now. But somehow this padding data has to be created, maybe it's random, maybe not. That takes a bit of time. I will commit a new version of my plugin in a few secs, maybe it works after that.

**Comment by onepiecefreak3** [comment]
I now committed a randomization for the padding part. Could you try it again?

**Comment by Moonstriker** [comment]
The plugin worked!

**Comment by onepiecefreak3** [comment]
So it rly was just garbage data and had to be non-zero?
Well that... But ok I see this issue as solved then.
