### ISSUE TITLE
Gundam The 3D Battle APK files

### ISSUE THREAD

**Issue by Deathmaw** [IcySon55/Kuriimu#332]
Issue: Plugin Request
Console: 3DS
Format extension(s): apk
Type: Archive
Game Name: Gundam The 3D Battle

First 8 byte of file(s):
apk - [45 4E 44 49 4C 54 4C 45] - [ENDILTLE]

More details:
Game seems to pack everything in "apk" files, also comes with a "idx" file that looks like it contains filenames.

Sample files (if possible):
https://mega.nz/#!F8ZhiShB!R5pHsdhISMpm4seyhYv66YjM7Vy1E8PS9WoIHrhugP8

**Comment by onepiecefreak3** [comment]
Well files seem ZLib compressed.

**Comment by onepiecefreak3** [comment]
The pack.idx seems to be an index file, which references all files from the apk's.
However, each apk is self-contained and can be edited as such. Since multiple, independant files are related to a single index file, some limitations have to be imposed on the plugin. I cannot tell what those limitations are yet.

**Comment by onepiecefreak3** [comment]
This is now fully implemented in Kuriimu2's newest dev build and upcoming Release 1.2.1.
This plugin can open the pack.idx and apk files in the same folder.

Important notice to the proper usage:
Since pack.idx references data from the apk files, it is advised to only ever open the pack.idx in presence of the 5 apk files. Not doing so, will lead to the plugin not finding all the necessary information to fully load the list of files. Saving the pack.idx in such a state may get rid of many files important to the game.

The pack.idx can be loaded even if there apk's missing, but above restrictions and warnings apply.
Each apk can be opened by itself as well, but this will not update information in the pack.idx, which is assumed to hold the actual authority of the game finding files in them. So it is adviced against directly editing the apk files, they will get automatically updated if the pack.idx is edited.

If there are more questions or requests regarding this format, refer to the Kuriimu2 github in the future.
