### ISSUE TITLE
Gaki no Tsukai 3DS (rtex / memfs)

### ISSUE THREAD

**Issue by SonofUgly** [IcySon55/Kuriimu#335]
Issue: plugin request
Console: 3DS
Format extension(s): .rtex / .memfs
Type: image / archive
Game Name: ダウンタウンのガキの使いやあらへんで!! 絶対に捕まってはいけないガースー黒光りランド [Downtown no Gaki no Tsukai Yaarahen de!! Zettai ni Tsukamatte Haikenai Gasu Kurobikari Land]

First 8 byte of file(s):
.rtex - 5254455800000000 - RTEX....
.memfs - 52534F4E - RSON

More details:
Only the 4 first bytes are the same in the .memfs files.
The game was developed by [Alchemist](https://en.wikipedia.org/wiki/Alchemist_%28company%29) and uses Criware.

Sample files (if possible):
[RTEX Samples](http://www.mediafire.com/file/2d3xki3b3s3tgp8/Gaki_rtex_samples.zip)
[MemFS Samples](https://www.mediafire.com/file/mqxztxlmxzgs4nl/Gaki%20memfs%20samples.zip)

**Comment by onepiecefreak3** [comment]
Based on information online, the game was developed by Planet G. Alchemist only published it.

**Comment by onepiecefreak3** [comment]
The RSON format seems to be a binary JSON-like structure. However, it doesn't seem to be a known standard, as per my research.
What I found out about the format is:
1. At the end of the file there seem to be the file information. In those are strings prefixed by the string identifier 0x88 and its length in 1 byte. Strings are encoded in Unicode. Strings are null-terminated, but the string length doesn't account said null-terminator.
2. If the RSON contains binary data, it is contained in a 6 byte header. A 2-byte magic "RZ" followed by a big endian integer denoting the decompressed size of the following ZLib-compressed data.
3. Said binary data container is prefixed by its compressed length in 2 bytes, which is not always the case and may be in part because of the binary serialization.

Since this format is currently too complex to take on, I will close this issue without further work on it. If you can achieve more information on it, feel free to open an issue requesting memfs again on the Kuriimu2 github.
