### ISSUE TITLE
.bimg Images (Thumbnails for eShop video titles)

### ISSUE THREAD

**Issue by CebolaBros64** [IcySon55/Kuriimu#349]
**Issue:** Plugin request
**Console:** 3DS
**Format extension(s):** .bimg
**Type:** Image
**Game Name:** Most (if not all) video titles from the eShop

**First 8 byte of file(s):**
.bimg - [00 00 00 00 00 00 01 00] - [........]

**More details:**
These files are used for the thumbnails on video titles (eg. Shaun the Sheep, Kirby: Right Back at Ya 3D, Kid Icarus Shorts, Dinosaur Office...)

[This GBATemp thread](https://gbatemp.net/threads/how-to-open-bimg-images.434231/) has some info about it and there's a converter [over here](https://github.com/walterclozet/bimg_conv).

**Sample files (if possible):**
https://drive.google.com/open?id=0B5n4g7VtUcGBOWIyNEh0dml1dTg

**Comment by onepiecefreak3** [comment]
Support for this format was added in the newest dev build and upcoming Release 1.2.1 of Kuriimu2.
This is a manual plugin, because the format cannot be identified automatically. To open this format select the plugin "BIMG" under "plugin_nintendo.dll".
For future format support or bugs reports, please refer to Kuriimu2.
