### ISSUE TITLE
Some .xa files in Professor Layton and the Miracle Mask are won't open

### ISSUE THREAD

**Issue by itstake** [IcySon55/Kuriimu#384]
Issue: [bug report]
Console: 

System.ArgumentOutOfRangeExcetion, variable name: length
location: Kuriimu.IO.SubStream.ctor(Stream baseStream, Int64 offset, Int64 length)
location: archive_level5.XPCK.XPCK.ctor(Stream Input)
location: archive_level5.XPCK.XpckManager.Load(String filename)
location: Karameru.Manager.OpenFile(String filename)
Format extension(s): .xa
Type: [archive]
Game Name: Professor Layton and the Miracle Mask

First 8 byte of file(s):
.xa - 58 50 43 4B 12 50 05 00 3B - XPCK.P..;

More details:
I'm using non-english windows. Because of that, I translated error messages so It's not exactly same as original english messages.

Sample files (if possible):
[Download File](https://drive.google.com/open?id=1A567CBJQGhMhRq4tdsu9-v6-s0HGmKkI)

**Comment by onepiecefreak3** [comment]
According to header information and other information in the fileEntries this xa isn't valid. I checked every possible information and the whole archive should be 0x18d988 bytes big according to the header. Your title_a.xa is only 0x8dac4 which objects the header and the entries completely.
Please check the origin of this archive and don't use other tools to open and recreate XPCK's since other tools don't have that much information on their structure and can produce more structural errors.

I will close this issue as invalid here. Please reopen, if you find information against my argument.

**Comment by itstake** [comment]
Ok, So this file is not invaild. But this file is not edited or extracted by other tools. I just used karameru and [DotNet3DSToolkit](https://github.com/evandixon/DotNet3dsToolkit/releases) for extract/unpack/repack. I unpacked UK rom of Professor Layton and the Miracle Mask, and I opened file named lt5_uk.fa on karameru which located in lt5/arc. and I extracted title_a.xa from karameru directly.

So two possibilities are exist:

1.Karameru extracted files(lt5_uk.fa or title_a.xa) is invaild.
-> But When I try to run a repacked rom which contains replaced files(which extracted by karameru, not edited), It runs well. So this is impossible.

2.Original File(title_a.xa) is already invaild before karameru open it.
-> I don't know it's possible. I attend lt5_uk.fa from original rom. Please review it.
[Download](https://drive.google.com/open?id=1qRLNpxjfPFOkKBEu6_0rEKjo5mncOyHz)
