### ISSUE TITLE
.xb and .xi bugs

### ISSUE THREAD

**Issue by AlePlumber** [IcySon55/Kuriimu#387]
Issue: bug report 
Console: 3ds
Format extension(s): .xb, .xi
Type: image
Game Name: Inazuma Eleven Go Galaxy

First 8 byte of file(s):

More details:
when i edit the images in a .xb file named skill_mini.xb a little bit of the images work but on too of the images when i try to open the program says: "none of the installed plugins are able to open the file"  but i have this issue with some random files at the reemplace folder time 
the  game shows correctly the files that i can open but the others nop

Sample files (if possible):
https://drive.google.com/open?id=1UuEEQPGQ0b0KBefPdlFEqztx4cLr8YFb
.

**Comment by onepiecefreak3** [comment]
Do not give only the edited and faulty file. I need at least one comparison obviously with the original. So in the future also adding the original file is appreciated.

**Comment by onepiecefreak3** [comment]
Also the plugin recreates the archive byte perfect in its original state.

**Comment by onepiecefreak3** [comment]
After some more testing on this matter, the names will remain the same and the entries are updated correctly. The paddings are also intact. Therefore the archive will be created in a way the game can read it and also the images can be reopened after saving. I couldn't reproduce the issue and I deem this issue as invalid then, since you seemed to use an older version of the plugin.
