### ISSUE TITLE
[Plugin Request] Mighty Gunvolt Burst .osbctr Image Files

### ISSUE THREAD

**Issue by jmanplaysgames** [IcySon55/Kuriimu#401]
Issue: plugin request
Console: 3DS
Format extension(s): .osbctr
Type: image
Game Name: Mighty Gunvolt Burst

First 8 bytes of the file(s):
.osbctr - [Different in each file] - [Different in each file]

More details:
The header is different for every osbctr file, so I don't think the header contains anything easily recognizable. There are a bunch of osbctr files, so I assume that if a plugin is made, it should work for all of them.

Sample files (if possible):
https://drive.google.com/open?id=1lQK-KU1SZ0-jwYWVfaUGVjk2BCdTyhXS

**Comment by jmanplaysgames** [comment]
Is there any updates on this? I'm just wondering if anyone is even working on this, a simple yes or no would be fine. Since I posted this, I've only found one thing that is similar between the files; the first 8 bytes of "Gunvolt.osbctr" and "Beck.osbctr" are the same and...... thats pretty much it. It feels like the first 8 bytes might be the size of the image, but the two files aren't the same size so it doesn't seem like that's the case. 

I wish I could have helped more, but this file format just doesn't make any sense.

**Comment by IcySon55** [comment]
I've been busy working on Kuriimu2 but since you're on top of this, let's take a look.

**Comment by onepiecefreak3** [comment]
@jmanplaysgames I would like you to hand over the decrypted exheader and code.bin.
I assume it's just a simple XOR, but I'm not 100% sure.

**Comment by piratesephiroth** [comment]
I'm not the OP but here it is
https://void.cat/f0d8d3d8efce6f781a81273a3f644c953ebfe9b4

**Comment by ZoruaLoL** [comment]
Yes please, not only for .osb and .osbcrt, but also .tb2 (possiblt text), .stb, .gtb, .bfb and and .bfgrp

**Comment by onepiecefreak3** [comment]
The files are encrypted with an in-house encryption scheme. Each file type in the game is encrypted by a different password, which are specified below. those passwords are confirmed working for at least "Bloodstained: Curse of the Moon" (3DS and PC version) and "Mighty Gunvolt Burst" (3DS).

Passwords (without the quotes)
.osbctr/.osb: "obj90210"
.bfbctr/.bfb: "bft90210"
.scbctr/.scb: "scroll90210"
.stb: "set90210"
.ttb: "txt20170401"

All file types not mentioned are not encrypted. Each mentioned file type is further compressed with standard ZLib, prefixed by the decompressed size.

The newest dev build and upcoming Release 1.2.1 of Kuriimu2 will contain the cipher for IntiCreates games, as well as a plugin for .osb and osbctr. Since such files cannot be identified automatically, one has to manually choose the plugin to load those files with. Choose "OSB" under "plugin_inti_creates.dll" to load those files. The plugin will then decrypt and decompress the file as necessary to show the contained images. Changes are also possible.

Be aware that the games could not be started on an emulator, even in their original state, so a test could not be performed that the plugin saves a valid osb. However, saving the files will result in a loadable file and will be as close to the original as possible (the compression quality may differ from the original)

Since all necessary information regarding this file format are disclosed in this comment and a support was added, this issue will be closed.

**Comment by ZoruaLoL** [comment]
Could this plugin be updated? Games like Blaster Master Zero 2 also use .osb but get the error message "Non-negative number required. (Parameter 'count')", even though other Inti Creates' games like Dragon Marked for Death load just fine

For some reason the Switch version of BMZ2 packed files for _all_ the other platforms, hope it helps for sampling:
[bmz2-osb-xbox-windows.zip](https://github.com/user-attachments/files/17016415/bmz2-osb-xbox-windows.zip)
[bmz2-osb-switch-playstation.zip](https://github.com/user-attachments/files/17016416/bmz2-osb-switch-playstation.zip)
