### ISSUE TITLE
god eater archive plugin request

### ISSUE THREAD

**Issue by amadeusnorn** [IcySon55/Kuriimu#431]
Issue: plugin request
Console: psv
Format extension(s): .rdp
Type: archive 
Game Name: God Eater Resurrection 

First 8 bytes of the file(s):
.rdp - 72 64 70 20 20 20 20 20

More details:
this archive has an existing plugin from quickbms. extraction is fine with that but re-importation is broken and ends up with missing files.

Sample files (if possible):
https://drive.google.com/open?id=17mGaamWP8WaZM3jWu1MZhWuvKD6tSLdb

**Comment by amadeusnorn** [comment]
system.res that lies in the same directory:
https://drive.google.com/open?id=186L0U_EBk8WYDm6oahLFUECyN485Q5AG

**Comment by onepiecefreak3** [comment]
This format will be deprecated with Kuriimu2 due to its dependant nature on the game and complexity of reverse engineering it. It is listed as "Deprecated" in our Format overview for Kuriimu2 as well.
If someone else is willing to take a look at it and create a proper plugin for Kuriimu2, they are free to do so. However we don't plan on further investigating it.
Issue closed.
