### ISSUE TITLE
Future Card BuddyFight

### ISSUE THREAD

**Issue by zeak6464** [IcySon55/Kuriimu#432]
Issue: Nothing showing up
Console: 3DS
Format extension(s): ctpk & rtz
Type: Text or Image
Game Name: 
フューチャーカード バディファイト 目指せ！バディチャンピオン！

First 8 bytes of the file(s):
80000200

More details:
We can already extract the files with 7zip, so provide the first 8 bytes of the decompressed files.
Issue that comes up is nothing is showing at all ! 

Sample files (if possible):
http://www.mediafire.com/file/g539dgf1813cl1x/title.rar
^CTPK
http://www.mediafire.com/file/bz15obpugyyuadv/script.rar
^RTZ

**Comment by onepiecefreak3** [comment]
After decompressing the files with WinRar using GZIP, the described bug cannot be reproduced in Kuriimu2.
It is assumed that porting the plugin fixed the issue. Since the samples are no longer avaialbe it is unknown if the bug is encountered only on some files that were not tested. Should the issue persist in your case, please refer to Kuriimu2 for any further bug reports on this format.
