### ISSUE TITLE
DPK Archive Request

### ISSUE THREAD

**Issue by AlternativeZero** [IcySon55/Kuriimu#435]
Issue: plugin request
Console: Playstation Vita
Format extension(s): .dpk
Type: archive
Game Name: Earth Defense Force 2017 Portable

First 8 bytes of the file(s):
.dpk - 52 49 46 46 5C 1B 00 00 - RIFF\...

More details:
It's the sound file used in Earth Defense Force 2017 Portable, I searched but couldn't find an existing unpacker and repacker which makes undubbing this game currently impossible.

Sample files (if possible):
https://drive.google.com/open?id=1f2jz7MKuhdLVnlWARqkM2ihCOFn9O0c-
https://drive.google.com/open?id=1jMqorE3ny3skksS69j6_nNh-ah6kCUCh
https://drive.google.com/open?id=1VjMcA7jD3tS3PiQ9h-oAh3udK8JdbOl8

**Comment by onepiecefreak3** [comment]
RIFF sounds like an audio file. Just my first impression by not looking at the file yet.

**Comment by AlternativeZero** [comment]
Sorry, didn't know it had an index file, it was in a different location.

Added it to the original link.

**Comment by IcySon55** [comment]
I'll be taking care of this one since I have a dumper already.

**Comment by IcySon55** [comment]
Sorry I mistook this format for something else.

**Comment by onepiecefreak3** [comment]
This format seems to be dependant on some external fileor the binary itself to extract the sound files from it.
Since all provided samples do not seem to help this extraction and the format is not self sustained, we will no longer pursue completion of this issue.
While the architecture of Kuriimu2 can add a plugin to extract this DPK, the work for this will not be done by us. A reverse engineer for your team specifically can do the task as well.
Therefore, Issue unresolved and closed.
