### ISSUE TITLE
Spike Chunsoft Compression

### ISSUE THREAD

**Issue by AlphaXeno** [IcySon55/Kuriimu#464]
Issue: Plugin Request
Console: Wii/PSVita
Format extension(s): 
Type: Text/Image
Game Name: 

First 8 bytes of the file(s):
0xFCAA55A7

More details:
<details>

Sample files (if possible):
https://mega.nz/#!KHJkULCb!y8V_7mbqKxkP19r90yBiQPNyq6ReFbmopgi3Z9mVDXA

**Comment by onepiecefreak3** [comment]
This compression is fully implemented in Kuriimu2. 98% of all files we encountered also compressed in a timely manner, unlike earlier implementations in Kuriimu1.
The other 2% of files can take up to hours due to how the match finding is implemented in our Kompression framework. This is a general problem, which, as you might see, is of less priority, since it affects not many files ever encountered.
However, it is being worked on. Therefore this issue gets closed.
