### ISSUE TITLE
improve display in high-dpi screen

### ISSUE THREAD

**Issue by WanderMax** [IcySon55/Kuriimu#472]
Issue: [feature request]
Console: 
Format extension(s): 
Type: [text | image]
Game Name: 

First 8 bytes of the file(s):

More details:
The latest version in high dpi screen (4K) shows the blurred UI as below, could you please improve display in high-dpi screen? 
Thanks.

Sample files (if possible):
![20180629204641](https://user-images.githubusercontent.com/15909056/42093099-c36c2ec2-7bdd-11e8-81f9-e10a30144907.png)

**Comment by IcySon55** [comment]
Sorry, fixing the blurry UI is not possible because Kuriimu is developed in WinForms. I've started working on Kuriimu2 but it won't be as capable for a long time.

**Comment by wabberz** [comment]
It's not like this makes a difference on the usefulness of the app. It's not as pretty, but it works. This should be the lowest priority of all things and it's not why Kuriimu 2.0 is in the works.

**Comment by WanderMax** [comment]
OK, thanks!

**Comment by onepiecefreak3** [comment]
We have no experience fixing such things. We can only hope that the underlying frameworks take care of it.
Kuriimu2 is based on EtoForms as GUI now and you can test if the blurryness still affects you with the newest dev build or any Release of it.
Since it's a pretty low priority and probably not an issue anymore, it gets closed.
