### ISSUE TITLE
Yuusha Shisu PSVita ARC [Karameru]

### ISSUE THREAD

**Issue by GowSupremo** [IcySon55/Kuriimu#485]
Issue: Bug report
Console: PSVita
Format extension(s): ARC
Type: Archive
Game Name: Yuusha Shisu

First 8 bytes of the file(s):
ARC - [41 52 43 00 00 01 F0 01] - [ARCð]

More details:
Opening ARC with Karameru shows this error:
![arc psvita yuusha shisu](https://user-images.githubusercontent.com/17249334/42588020-ccf69ee2-853c-11e8-809a-e7a646e0f20a.png)

Sample files (if possible):
https://mega.nz/#!QhkjwChL!g2OFBHiGNCkG8HXThsLjHt_SI2Ktgo1RE6lOjE90vxA

**Comment by onepiecefreak3** [comment]
Actually this archive is something different than MT Framework ARC. It gets falsely identified.

**Comment by GowSupremo** [comment]
It's a variant from ARC?

**Comment by onepiecefreak3** [comment]
No it isn't.

**Comment by onepiecefreak3** [comment]
This bug does not occur in Kuriimu2 anymore, since its framework was written to block false positives like this to happen ever again. If both the mt_framework and yuusha_shisu plugins are present, then Kuriimu2 will prompt the user to choose the plugin to use.
In this case here, one would choose the "PAC" plugin under "plugin_yuusha_shisu.dll" and the file is loaded correctly.
This behaviour is confirmed working in Kuriimu2, therefore this issue is closed.
