### ISSUE TITLE
Bug Report: cannot open some of Captain Toad 3DS's BFLIMs

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#494]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): bflim
Type: image
Game Name: Captain Toad: Treasure Tracker

First 8 bytes of the file(s):
It varies.

More details:
```---------------------------
BXLIM - Binary Layout Image Adapter
---------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at image_nintendo.BXLIM.BXLIM..ctor(Stream input)

   at image_nintendo.BXLIM.BxlimAdapter.Load(String filename)

   at Kukkii.Converter.OpenFile(String filename)
---------------------------
OK   
---------------------------
````

Sample files (if possible):
https://drive.google.com/open?id=1DqJ4kAvKC0LKw-rrJdzEdSCDpQxrIo_H

**Comment by Spmario233** [comment]
Kuriimu 1.0.9 works fine on these images. but the newest Kuriimu doesn't...

**Comment by onepiecefreak3** [comment]
In the newest dev build and upcomgin Release 1.2.1 of Kuriimu2, all the samples of bflim we ever encountered, in addition to those provided in this issue, work as expected. The only known issue, which isn't an issue with the plugin itself, is the loading of files with unusual characters in their names (like WidowID_00+t.bflim from Wind Waker HD).
Since this is not a problem related to the plugin itself, this issue will be closed.

Please refer to Kuriimu2 in the future, if you encounter more bugs with the plugin.
