### ISSUE TITLE
 Compressing files using Second version of the SpikeChunsoft compression algorithm freezes Kuriimu

### ISSUE THREAD

**Issue by froid-san** [IcySon55/Kuriimu#521]
Issue: bug report
Console: VITA
Format extension(s): .btx (.SHTX inside archive)
Type: archive
Game Name: Gun Gun Pixies

First 8 bytes of the file(s):
FC AA 55 A7 0C 71 16 00

More details:
Original file size is 364kb, extracted size is 1.40 MB, recompressed the orig extracted archive within 1st version compression of SpikeChunsoft compression algorithm. Compressed files becomes 1.04 MB. Game freezes with big archives. Second version compression algo thinking it would compress better. it just freezes the app regardless of the file size.

Sample files (if possible):
https://drive.google.com/open?id=1Vc4Bfo10DndE4uOXLtl_V_Aghlq9dooD

**Comment by onepiecefreak3** [comment]
It just takes forever. Like literal hours.
It was and is experimental and shouldn't be used. Use either the first version and try getting the archives loaded in the game like that or wait some hours.

It's also unlikely for now that the 2nd version gets improved since its approach is very imperformant.
