### ISSUE TITLE
I can‘t open the .amb files from the 3ds Sonic Generations

### ISSUE THREAD

**Issue by kawaws66** [IcySon55/Kuriimu#591]
Issue: plugin request/bug report(maybe?)--I can‘t open the .amb files
Console: nintendo 3ds
Format extension(s): .amb
Type: text/image(maybe?)
Game Name: Sonic Generations (USA edition)

First 8 bytes of the file(s):
Sorry,the files can't be opened

More details:
they can't be opened when I open these files and then it would appear like such a message
![QQ图片20190425015440](https://user-images.githubusercontent.com/49957659/56684047-7bbb2000-6701-11e9-8999-39dd1dc7d8bf.png)
I would appreciate if you could help me

Sample files (if possible):
<links>
[MENU（Sonic Generations USA edition，these files are unpacked from the cpk pack in cci file）.zip](https://github.com/IcySon55/Kuriimu/files/3113703/MENU.Sonic.Generations.USA.edition.these.files.are.unpacked.from.the.cpk.pack.in.cci.file.zip)
[MSG（Sonic Generations USA edition，these files are unpacked from the cpk pack in cci file）.zip](https://github.com/IcySon55/Kuriimu/files/3113704/MSG.Sonic.Generations.USA.edition.these.files.are.unpacked.from.the.cpk.pack.in.cci.file.zip)
[System（Sonic Generations USA edition，these files are unpacked from the cpk pack in cci file）.zip](https://github.com/IcySon55/Kuriimu/files/3113705/System.Sonic.Generations.USA.edition.these.files.are.unpacked.from.the.cpk.pack.in.cci.file.zip)

**Comment by onepiecefreak3** [comment]
This bug was caused by the files using Little Endian. Normally that's given, since the 3DS has a Little Endian architecture.
However, the samples we had of AMB, that also originated from a 3DS game (namely Dragon Ball Heroes: Ultimate Mission X) were weirdly in Big Endian. we assumed this was a quirk with the format itself and hardcoded the usage of Big Endian.

We fixed this behaviour to now detect the byte order in the newest dev version and upcoming Release of Kuriimu2.
This fix will not be enrolled in Karameru, since it is discontinued.

For more bug reports or requests, please refer to Kuriimu2 in the future.
