### ISSUE TITLE
.CXI file write issue in Karameru with Gyakuten Saiban 5/Ace Attorney Dual Destinies

### ISSUE THREAD

**Issue by Deniii2000** [IcySon55/Kuriimu#594]
Issue: bug report
Console: Nintendo 3DS
Format extension(s): CXI
Type: archive
Game Name: Gyakuten Saiban 5 / Phoenix Wright Ace Attorney: Dual Destinies

First 8 bytes of the file(s):
Phoenix Wright Ace Attorney: Dual Destinies:
GameData.CXI - 17 62 71 FE E5 28 DD 79 - bqþå(Ýy

Gyakuten Saiban 5:
GameData.CXI - 58 37 08 14 ED D8 F4 5F - X7íØô_

More details:
Opening the GameData.CXI file with Karameru and then writing it again with the "Save" or "Save As" function, breaks the file.
When trying to load the file in Citra, the emulator freezes, requiring the user to terminate the process with Task Manager.

No modification to the GameData.CXI file is needed to break it: replacing a file inside it or just opening and saving the .CXI as it is, will break the file in the same way.

This happens in the US and JP versions of the game. EU version not tested.
On both cases, GameData.CXI file was exctracted from a decrypted .3DS file.

Sample files (if possible):
https://mega.nz/#!NIdlDQSK!VM5vvq8Qrwr97dABwlIfGqrO4p5Tuh_xiQ4ZmB6NDWQ

**Comment by onepiecefreak3** [comment]
This issue can not be reproduced on the newest dev build of Kuriimu2. It is likely that the issue was fixed as it was reported by others while Kuriimu2 was developed and got Karameru's plugins ported over.
We have multiple teams that can use Kuriimu2 without problems on saving any kind of .3ds, .cia, or .cxi file by now.
This issue will therefore be closed.
