### ISSUE TITLE
World_Neverland_Qukria_Oukoku_Monogatari

### ISSUE THREAD

**Issue by Necron00** [IcySon55/Kuriimu#601]
Issue: [plugin request]
Console: PSP
Format extension(s): BIN BBS SBSS TEXT ETC
Type: [text | image | archive]
Game Name: World_Neverland_Qukria_Oukoku_Monogatari

First 8 bytes of the file(s):
<extension> - [bytes in hex] - [bytes in ASCII]

More details:
Sorry still new at this kind of thing

Sample files (if possible):
https://drive.google.com/drive/folders/1DZF5L2zqSnC5BPsROLuGffxJjMD18mhf?usp=sharing

**Comment by onepiecefreak3** [comment]
Due to the samples no longer availabel, and the information not provided properly (or way too broadly), this issue will be closed without being processed further.

For future requests, please refer to Kuriimu2. Also, please do some research on your own.
The issue makes it clear that you should provide some information beforehand, like the type of file. It is ok if you cannot provide this information after your own research, but we want you to do some at least. Note everything in the details.

You should also not open an issue for x different formats. One issue per format.
