### ISSUE TITLE
Error when trying to extract some Super Mario Maker 3ds Bflim files

### ISSUE THREAD

**Issue by Machow8** [IcySon55/Kuriimu#612]
**Describe the bug**
When i try to extract some bflim files from Super Mario Maker 3ds game, the following error appears: http://prntscr.com/oktbaw (translation of 'A chave fornecida não estava presente no dicionário' ->'The supplied key wasn't present in the dictionary').

**To Reproduce**
1. Go to Batch Tab > choose Batch Export PNG option;
2. In new window select where blfim file is stored at;
3. Click ok button;
4. See the described error.

Note: Or, to simplify, grab one of said blfim files and drop it in Kukkii window to simplify this. All blfim files which make Kukkii show that error were uploaded to cloud and the download url is show at **Additional context** of this message.

**Expected behavior**
What is expected is that every graphics file be extracted from bflim file.

**Screenshots**
This is supplied in **Describe the bug** section of this message.

**Desktop (please complete the following information):**
 - Version [e.g. 22]: Kukkii v1.0.14-e086e7f

**Additional context**
The download url for said bflim files is: https://www.mediafire.com/folder/hb09lxsytcnus/smm3ds

I hope this is fixed soon, so, i'm able to fullfill this page: https://tcrf.net/Super_Mario_Maker_for_Nintendo_3DS after being sure that every unused stuff was found.

Thanks!

**Comment by onepiecefreak3** [comment]
The problem most likely lies in a missing image encoding in the plugins dictionary. There currently are some image encoding Kuriimu is unable to handle, either due to complexity (in understanding it) or because it's unknown.

**Comment by El-Vallo** [comment]
Hi,

This seems something that can be easily fixed by developer, so, i hope it's easy to fix.

I had find some unused stuff in SMM3ds which i had shown here: https://tcrf.net/Super_Mario_Maker_for_Nintendo_3DS and i wanna see if there is more unused stuff left in game files.

I'll be waiting then. :)

**Comment by onepiecefreak3** [comment]
The newest dev build of Kuriimu2 contains most of the image encodings we ever encountered by now. Since your samples are not available anymore, I can just assume that porting over the plugin and enriching missing encodings over time already solved this issue.

If not, please refer to Kuriimu2 for bug reports and requests.

**Comment by Machow8** [comment]
> The newest dev build of Kuriimu2 contains most of the image encodings we ever encountered by now. Since your samples are not available anymore, I can just assume that porting over the plugin and enriching missing encodings over time already solved this issue.
> 
> If not, please refer to Kuriimu2 for bug reports and requests.

I didn't try again after said updates. I'll check again.

If issues are fixed, i'll let you know.
