### ISSUE TITLE
MT Texture

### ISSUE THREAD

**Issue by wabberz** [IcySon55/Kuriimu#615]
**Describe the bug**
The plugin can convert all textures in DGS2 except for 63 in the Android version and one single texture in the 3DS version.

**To Reproduce**
1. Open any of the attached textures

**Expected behavior**
I expect them to be displayed 🤔 

**Desktop (please complete the following information):**
 - Version git master

**All textures the plugin choked on:**
[mttex_bug_20190814.7z](https://mega.nz/#!4NxywawQ!Jq33PhW0Rgtd2h9TvF077L3MT5FZpMht-TW_fowfsYA) (2.4MB)

**Comment by onepiecefreak3** [comment]
The mentioned bugs were fixed in the newest dev build of Kuriimu2.
Apparently one MTTex can contain multiple image. However, all images share the same dimensions, mip count, and encoding.
Only one to four tex found in each known game have this property. Those are also most likely never used by the game.
Issue closed.
