### ISSUE TITLE
Yo-kai Watch Switch Version

### ISSUE THREAD

**Issue by xoloti** [IcySon55/Kuriimu#626]
Game Name:  Yo-kai Watch For Nintendo Switch
Console:  Nintendo Switch
Format extension(s): .xi
Type: image

First 8 bytes of the file(s):
<extension> - 494D474E - IMGN

More details:
Well it seems that its similar to the 3ds version, so i've copied IMGC files in kuriimu and changed to IMGN. Also i've see that this files are rgba (8,8,8,8) but swapchannels must be set True because if u put false (default) the image seems to be negative. The problem is that the result pic is a lot of pixeled.

![image](https://user-images.githubusercontent.com/56635976/67163024-9269c900-f36a-11e9-92da-ef8d35f362f7.png)

Sample files (if possible):
https://drive.google.com/open?id=134BUJ6_j3aqzbSX20KHCJKe3zCndknrE

Thanks and sorry for my english

**Comment by HucetJ** [comment]
> 
> 
> Game Name: Yo-kai Watch For Nintendo Switch
> Console: Nintendo Switch
> Format extension(s): .xi
> Type: image
> 
> First 8 bytes of the file(s):
> - 494D474E - IMGN
> 
> More details:
> Well it seems that its similar to the 3ds version, so i've copied IMGC files in kuriimu and changed to IMGN. Also i've see that this files are rgba (8,8,8,8) but swapchannels must be set True because if u put false (default) the image seems to be negative. The problem is that the result pic is a lot of pixeled.
> 
> ![image](https://user-images.githubusercontent.com/56635976/67163024-9269c900-f36a-11e9-92da-ef8d35f362f7.png)
> 
> Sample files (if possible):
> https://drive.google.com/open?id=134BUJ6_j3aqzbSX20KHCJKe3zCndknrE
> 
> Thanks and sorry for my english

Hi Xoloti, I will able to help you with the YW1S pictures, how can I reach you directly ?
Thank you !

**Comment by onepiecefreak3** [comment]
The pixelation originates from the usage of the IMGC plugin.
IMGC is encountered on the 3DS which needs to apply a Z-Order swizzle on the image. This swizzle however, is not present on the switch, but will be applied here, due to the change from IMGN to IMGC.

Kuriimu2 Release 1.2.0 and up and its newest dev build have proper support for IMGN, the switch swizzle algorithm, and the encodings used on the switch.

Since this bug can not be reproduced as stated in Kuriimu2, it gets closed.
