### ISSUE TITLE
Typing Polish letters don't work

### ISSUE THREAD

**Issue by klaudi30i** [IcySon55/Kuriimu#630]
When i have to type a Polish letter like ś or ą on Kuriimu windows blinking and nothing happen.

**Comment by onepiecefreak3** [comment]
The polish letter bug was laready reported in another issue here: https://github.com/IcySon55/Kuriimu/issues/570
As found out, this problem also occurred in other applications, which makes it possible to be a system issue.
Since less information is provided here, I assume the same circumstances and close the issue.
