### ISSUE TITLE
Some ACNL .bcgrp archives do not open in Karameru

### ISSUE THREAD

**Issue by Chubby-Bub** [IcySon55/Kuriimu#655]
**Describe Bug**
Certain .bcgrp files (from Animal Crossing: New Leaf) will not open. Either they will open and the program says there are files within but they are not there, or a window will say "None of the installed programs were able to open this file" despite other .bcgrp files from the same game working

**To Reproduce**
1. Open Karameru
2. Click on Open
3. Try to open a .bcgrp archive

**Expected behavior**
The .bcgrp file would be extracted into its contained .bcwav files. See first screenshot

**Screenshots**
One of the files properly opening: ![Capture](https://user-images.githubusercontent.com/65587508/82292437-c5575800-995f-11ea-8550-75c5cca1439d.PNG)

Another file opening but not showing its contents (note at the bottom it says Files: 7): 
![Capture3](https://user-images.githubusercontent.com/65587508/82292911-8c6bb300-9960-11ea-88d7-94f971b053a9.PNG)

Another file simply not opening at all:

![Capture 2](https://user-images.githubusercontent.com/65587508/82292536-f2a40600-995f-11ea-8ef5-30ecc85612af.PNG)

**Desktop (please complete the following information):**
 - Version 1.0.14

**Additional context**
Here are the files in question. So far the only one that opens successfully was the "Island" one.
https://drive.google.com/open?id=121Jvec2ipVWftO2YZVqN6L33uwXrP51l

**Comment by onepiecefreak3** [comment]
The file not opening at all could mean, that its content is compressed or just not supported, despite what the extension suggests.
Judging by the plugins that opened the other files, there is no bcgrp plugin at all. The first one was detected to be a CWAR, while the second one was falsely detected to be some binary archive from Mario Maker.
The issue here is that there is no common bcgrp format. That is only believed because of the extensions.

This issue will be closed, since it cannot be resolved as requested.
