### ISSUE TITLE
Inazuma Eleven GO Strikers 2013 -- BLN Archive format

### ISSUE THREAD

**Issue by GalacticPirate-Prog** [IcySon55/Kuriimu#660]
Game Name: Inazuma Eleven GO Strikers 2013
Console: Wii
Format extension(s): *.bln
Type: archive

First 8 bytes of the file(s):
mcb0.bln - `00 00 3F 00 00 00 00 00` - `��?�����`
mcb1.bln - `03 00 00 00 00 C0 1E 00` - `����À�`

More details:
mcb0.bln seems to be a 12-byte wide table that contains offsets and sizes used to extract the data. The offsets and sizes are in little endian. mcb1.bln is the actual archive and contains the actual compressed game files, some using widespread formats like BRRES and others using more obscure ones like the SHTXFS textures used in some Danganronpa games.

Sample files (if possible):
[https://mega.nz/file/SEkR0bAS#oSqY3MpD2flSkvnl78JZ2LWDYL9b67VZ3xbfBzw0mcE](url)
[https://mega.nz/file/6IlTCLLJ#1eYM4GNAjhC96fVnFkEsnhlp-dvMPwQDyV--nHT40Js](url)

**Comment by hero442** [comment]
You solved?

**Comment by onepiecefreak3** [comment]
This format and subsequent SHTX support is done/is being worked on in Kuriimu2.
BLN is fully implemented with restrictions due to the games logic (files cannot be larger than there original).
SHTX is supported, but is currently part of a refactoring effort, and will be available at a later date.
This issue will be closed, since all the logic exists already.
